package com.test.mycat.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_order.order_id
     *
     * @mbggenerated
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_order.order_no
     *
     * @mbggenerated
     */
    private String orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_order.amount
     *
     * @mbggenerated
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_order.buyer_id
     *
     * @mbggenerated
     */
    private Long buyerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_order.buer_name
     *
     * @mbggenerated
     */
    private String buerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_order.seller_id
     *
     * @mbggenerated
     */
    private Long sellerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_order.seller_name
     *
     * @mbggenerated
     */
    private String sellerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_order.product_id
     *
     * @mbggenerated
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_order.product_name
     *
     * @mbggenerated
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_order.order_status
     *
     * @mbggenerated
     */
    private Integer orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_order.add_time
     *
     * @mbggenerated
     */
    private Date addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_order.add_by
     *
     * @mbggenerated
     */
    private Long addBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_order.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_order.update_by
     *
     * @mbggenerated
     */
    private Long updateBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_order.order_id
     *
     * @return the value of bus_order.order_id
     *
     * @mbggenerated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_order.order_id
     *
     * @param orderId the value for bus_order.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_order.order_no
     *
     * @return the value of bus_order.order_no
     *
     * @mbggenerated
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_order.order_no
     *
     * @param orderNo the value for bus_order.order_no
     *
     * @mbggenerated
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_order.amount
     *
     * @return the value of bus_order.amount
     *
     * @mbggenerated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_order.amount
     *
     * @param amount the value for bus_order.amount
     *
     * @mbggenerated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_order.buyer_id
     *
     * @return the value of bus_order.buyer_id
     *
     * @mbggenerated
     */
    public Long getBuyerId() {
        return buyerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_order.buyer_id
     *
     * @param buyerId the value for bus_order.buyer_id
     *
     * @mbggenerated
     */
    public void setBuyerId(Long buyerId) {
        this.buyerId = buyerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_order.buer_name
     *
     * @return the value of bus_order.buer_name
     *
     * @mbggenerated
     */
    public String getBuerName() {
        return buerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_order.buer_name
     *
     * @param buerName the value for bus_order.buer_name
     *
     * @mbggenerated
     */
    public void setBuerName(String buerName) {
        this.buerName = buerName == null ? null : buerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_order.seller_id
     *
     * @return the value of bus_order.seller_id
     *
     * @mbggenerated
     */
    public Long getSellerId() {
        return sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_order.seller_id
     *
     * @param sellerId the value for bus_order.seller_id
     *
     * @mbggenerated
     */
    public void setSellerId(Long sellerId) {
        this.sellerId = sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_order.seller_name
     *
     * @return the value of bus_order.seller_name
     *
     * @mbggenerated
     */
    public String getSellerName() {
        return sellerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_order.seller_name
     *
     * @param sellerName the value for bus_order.seller_name
     *
     * @mbggenerated
     */
    public void setSellerName(String sellerName) {
        this.sellerName = sellerName == null ? null : sellerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_order.product_id
     *
     * @return the value of bus_order.product_id
     *
     * @mbggenerated
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_order.product_id
     *
     * @param productId the value for bus_order.product_id
     *
     * @mbggenerated
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_order.product_name
     *
     * @return the value of bus_order.product_name
     *
     * @mbggenerated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_order.product_name
     *
     * @param productName the value for bus_order.product_name
     *
     * @mbggenerated
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_order.order_status
     *
     * @return the value of bus_order.order_status
     *
     * @mbggenerated
     */
    public Integer getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_order.order_status
     *
     * @param orderStatus the value for bus_order.order_status
     *
     * @mbggenerated
     */
    public void setOrderStatus(Integer orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_order.add_time
     *
     * @return the value of bus_order.add_time
     *
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_order.add_time
     *
     * @param addTime the value for bus_order.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_order.add_by
     *
     * @return the value of bus_order.add_by
     *
     * @mbggenerated
     */
    public Long getAddBy() {
        return addBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_order.add_by
     *
     * @param addBy the value for bus_order.add_by
     *
     * @mbggenerated
     */
    public void setAddBy(Long addBy) {
        this.addBy = addBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_order.update_time
     *
     * @return the value of bus_order.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_order.update_time
     *
     * @param updateTime the value for bus_order.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_order.update_by
     *
     * @return the value of bus_order.update_by
     *
     * @mbggenerated
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_order.update_by
     *
     * @param updateBy the value for bus_order.update_by
     *
     * @mbggenerated
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }
}