package com.test.mycat.domain.vo;

import lombok.Data;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * @Auther: huang
 * @Date: 2019/5/15 11:09
 * @Description:
 */
@Data
public class OrderVo implements Serializable{

    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_order.order_no
     *
     * @mbggenerated
     */
    private String orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_order.amount
     *
     * @mbggenerated
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_order.buyer_id
     *
     * @mbggenerated
     */
    private Long buyerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_order.buer_name
     *
     * @mbggenerated
     */
    private String buerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_order.seller_id
     *
     * @mbggenerated
     */
    private Long sellerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_order.seller_name
     *
     * @mbggenerated
     */
    private String sellerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_order.product_id
     *
     * @mbggenerated
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_order.product_name
     *
     * @mbggenerated
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_order.order_status
     *
     * @mbggenerated
     */
    private Integer orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_order.add_time
     *
     * @mbggenerated
     */
    private Date addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_order.add_by
     *
     * @mbggenerated
     */
    private Long addBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_order.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_order.update_by
     *
     * @mbggenerated
     */
    private Long updateBy;

}